//I at the end mean user going to Input
export const imageI='image'
export const newsI='news'
export const changeTaskPropI='changeTaskProp'
export const changeTaskTitleI='changeTaskTitle'
export const changeTaskTimeI='changeTaskTime'
export const addCityI='addCity'
export const findCityI='findCity'
export const deleteCityI='deleteCity'
export const titleI='title'
export const hoursI='hours'
export const editTaskI='editTask'
export const deleteTaskI='deleteTask'